spring.application.name=Course-Registration-System

# MongoDB configuration
# spring.data.mongodb.uri=mongodb+srv://rajeshwaranraj2002:9nRCd50kM0cfZYO1@rajeshwaran.yoskb66.mongodb.net/?retryWrites=true&w=majority&appName=Rajeshwaran

spring.data.mongodb.database=course_reg_sym

spring.data.mongodb.uri=mongodb://localhost:27017/


# Optional: enable MongoDB logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
